/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AbstractJsonSchemaPropertyObject } from './models/abstract-json-schema-property-object';
export type { CustomUrlRequest } from './models/custom-url-request';
export type { EntityModelUrlShortened } from './models/entity-model-url-shortened';
export type { Item } from './models/item';
export type { JsonSchema } from './models/json-schema';
export type { Link } from './models/link';
export type { Links } from './models/links';
export type { PagedModelEntityModelUrlShortened } from './models/paged-model-entity-model-url-shortened';
export type { PageMetadata } from './models/page-metadata';
export type { RepresentationModelObject } from './models/representation-model-object';
export type { RequestUrl } from './models/request-url';
export type { UrlShortened } from './models/url-shortened';
export type { UrlShortenedRequestBody } from './models/url-shortened-request-body';
