/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntityModelUrlShortened } from '../../models/entity-model-url-shortened';

export interface GetItemResourceUrlshortenedGet$Params {
  id: string;
}

export function getItemResourceUrlshortenedGet(http: HttpClient, rootUrl: string, params: GetItemResourceUrlshortenedGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EntityModelUrlShortened>> {
  const rb = new RequestBuilder(rootUrl, getItemResourceUrlshortenedGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/hal+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EntityModelUrlShortened>;
    })
  );
}

getItemResourceUrlshortenedGet.PATH = '/urlShorteneds/{id}';
