/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntityModelUrlShortened } from '../../models/entity-model-url-shortened';
import { UrlShortenedRequestBody } from '../../models/url-shortened-request-body';

export interface PostCollectionResourceUrlshortenedPost$Params {
      body: UrlShortenedRequestBody
}

export function postCollectionResourceUrlshortenedPost(http: HttpClient, rootUrl: string, params: PostCollectionResourceUrlshortenedPost$Params, context?: HttpContext): Observable<StrictHttpResponse<EntityModelUrlShortened>> {
  const rb = new RequestBuilder(rootUrl, postCollectionResourceUrlshortenedPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/hal+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EntityModelUrlShortened>;
    })
  );
}

postCollectionResourceUrlshortenedPost.PATH = '/urlShorteneds';
