/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UrlShortened } from '../../models/url-shortened';

export interface GetOriginalUrl$Params {
  shortUrl: string;
}

export function getOriginalUrl(http: HttpClient, rootUrl: string, params: GetOriginalUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<UrlShortened>> {
  const rb = new RequestBuilder(rootUrl, getOriginalUrl.PATH, 'get');
  if (params) {
    rb.query('shortUrl', params.shortUrl, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/hal+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UrlShortened>;
    })
  );
}

getOriginalUrl.PATH = '/shorten/GetOriginal';
