/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UrlShortened } from '../../models/url-shortened';

export interface GetAllUrls$Params {
}

export function getAllUrls(http: HttpClient, rootUrl: string, params?: GetAllUrls$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UrlShortened>>> {
  const rb = new RequestBuilder(rootUrl, getAllUrls.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/hal+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UrlShortened>>;
    })
  );
}

getAllUrls.PATH = '/shorten/';
