/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RequestUrl } from '../../models/request-url';
import { UrlShortened } from '../../models/url-shortened';

export interface UpdateUrl$Params {
  id: string;
      body: RequestUrl
}

export function updateUrl(http: HttpClient, rootUrl: string, params: UpdateUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<UrlShortened>> {
  const rb = new RequestBuilder(rootUrl, updateUrl.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/hal+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UrlShortened>;
    })
  );
}

updateUrl.PATH = '/shorten/update/{id}';
