/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Links } from '../models/links';
export interface EntityModelUrlShortened {
  '_links'?: Links;
  accessCount?: number;
  createdAt?: string;
  originalUrl?: string;
  shortenedUrl?: string;
  type?: string;
  updatedAt?: string;
}
