/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AbstractJsonSchemaPropertyObject } from '../models/abstract-json-schema-property-object';
export interface Item {
  properties?: {
[key: string]: AbstractJsonSchemaPropertyObject;
};
  requiredProperties?: Array<string>;
  type?: string;
}
