/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntityModelUrlShortened } from '../models/entity-model-url-shortened';
import { Links } from '../models/links';
import { PageMetadata } from '../models/page-metadata';
export interface PagedModelEntityModelUrlShortened {
  '_embedded'?: {
'urlShorteneds'?: Array<EntityModelUrlShortened>;
};
  '_links'?: Links;
  page?: PageMetadata;
}
