/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Links } from '../models/links';
export interface RepresentationModelObject {
  '_links'?: Links;
}
