/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UrlShortened {
  accessCount?: number;
  createdAt?: string;
  id?: number;
  originalUrl?: string;
  shortenedUrl?: string;
  type?: string;
  updatedAt?: string;
}
