/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntityModelUrlShortened } from '../../models/entity-model-url-shortened';

export interface ExecuteSearchUrlshortenedGet$Params {
  shortenedUrl?: string;
}

export function executeSearchUrlshortenedGet(http: HttpClient, rootUrl: string, params?: ExecuteSearchUrlshortenedGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EntityModelUrlShortened>> {
  const rb = new RequestBuilder(rootUrl, executeSearchUrlshortenedGet.PATH, 'get');
  if (params) {
    rb.query('shortenedUrl', params.shortenedUrl, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/hal+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EntityModelUrlShortened>;
    })
  );
}

executeSearchUrlshortenedGet.PATH = '/urlShorteneds/search/findByShortenedUrl';
